### ISSUE TITLE
Option for short delay

### ISSUE THREAD

**Issue by chrisgrieser** [rareitems/hl_match_area.nvim#1]
When scrolling through a document, every time I land on a bracket, the highlight flashes briefly, which is a bit distracting.

An option to have a short delay before the highlight appears could be useful to prevent this. What I think most "highlight cursor-word"-style plugins do updating based on `updatetime`?

**Comment by rareitems** [comment]
It was annoying me too. Added a delay (by default 100ms, can be changed in config) before applying the highlight
