### ISSUE TITLE
excluding delimiters?

### ISSUE THREAD

**Issue by gilbh** [rareitems/hl_match_area.nvim#3]
Love this plugin!

Is there a way to exclude a delimiter in the configuration? For me, it's `<` since I work in Python and it marks weird areas like this:
![image](https://user-images.githubusercontent.com/39532610/216199236-41c1c7c7-db37-412a-9a22-5e9ba49eed3c.png)

Thanks!

**Comment by rareitems** [comment]
Hi
I removed the hardcoded delimiters and it now relies or vim.opt.matchpairs so if you don't have '<' and '>' in that option it won't highlight those characters.
